language: java

addons:
  apt:
    packages:
    - graphviz
    - xmlstarlet

jdk:
- oraclejdk11

install: skip

script:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- if ./can_auto_deploy.sh  ; then mvn deploy -B -U --settings settings.xml; else mvn verify -B -U; fi

env:
  global:
  - secure: suNj41sc7HJaOwYaRE9gGvnGiFpJJ1nzLQ+AxkEGiy+1E6JdoVBlA73jcrXaokgIP2xk7t5aotTpUWSBglTXSBlcCNnh2NmbOFiVOyN4PJ3yEiP5ypF907tUdMVfumkSGdHMv/xSAzcjMMeguijVl6QkjN++USoa7OU9c9xsliIrIkKB//7qGWK8AbVE14hbRC3qKRpTH28jtSpWWnJ4mrsWn/WyaZCb9nzPPngy3bddmWt4tDuJ0/Ut5fsOhubYZ8ndhZjCKbSQC2p2CyPyoOmmC1CizIMqlcM5szfrL4UKdOVuxoeKHcO/jwbqLY+yWAYI0NFTlEHO0SBM8wO30Nrg7sXAzvdljYXC8QzMl6nys15QeXRvjs1+/vHZSPqF0WmuslPQeBI8auXHyJwR2p/+FsNfZ7oAh50IFd30seuymVevIusHKnrTdyctdj9Tfc4oIfBTgTDdrty8d3QRmeXUSfv8jRkYvoX3CaYXQk5ZAgmNBJeB6pTxAMTn17cttruNAo2ipTnuB2pYz/bjfC25R9G5En0GIgX5ROrXJ8RKDT1jWOIsa4JmQ2RyxnR06YfuUAD8wNcoBWeXr3yL+WdcbbyCXy5j/Won2zjpGuch2qhwI3re3uoBRyTefFp+BWLSxNfpV9YvWTKuCzRkYwkT6w1bxUDUTnp86twreEs=
  - secure: 1greULg96KRLXPIzjzn+BPYD6IsPp1efjIQUlyaovQYgVh/oa7hB5h7LXcUpOlOizOmACaUW8LUkeSZ2VvjEVZjGIhAAnE7ZmvoS54wL8Tl6FvJOO9bEu+NJQzpCnbuG1SfHGVIBQ72FfFFdQC/HbUEoMSrX3BTmnTb0rmooDYl/2t7i2m594HZ2fApfhuhp3NoRS82qbZ4n4fLE+em28Cm5/azR+Xp9XLJOifi1bl6F8uZMjSM8duxAM/iyAQdl/HsqPnwyirAUdj5J9WTYTdIXtBVF1qLEJxFPXB6U5wCFBD9C30zoF/+iUlrnJlhIknSbyzRjmxTvUhnl3ovSpREEqjxH1Dz5ImsKsl3KrDKm2L+68H6fHc9UoHQk3yQz46O63E0u3P24D0OMVpEKpMyhf4CMewriUg3CC22Cd6mhRHjBd6XDS9oyAugAx9wCb9OaFIY7y1soQwFt+cD+X5VX0wtCBK0v3YDeRg3mgFU1oR/dhssgSlotuQOpjeYAfC73FyUMxLiktLyZ8YZeMb0Z38gvtGMcmVBKXrjB+aRIUto8D+qhy8F/qbhTJjZuLOCmraJfmnWyk7piBoGWBFAK8uUCAkZY/GSkyRiAb9slilOZaC8rtIRHfuluHEgejQ0/eUdfScuh29Tc+dIbPhHEQfn5HIUDWcq7hKgfJYs=
