name: Verify

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Verify
        run: mvn -B -U verify

      - name: Read build.log
        id: build
        uses: juliangruber/read-file-action@v1
        with:
          path: ./target/its/add_aggregate/build.log

      - run: echo "${{ steps.build.outputs.content }}"
